server:
  port: 8000
spring:
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/atcrowdfunding_1009?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filter: stat #开启监控过滤器
  redis:
    host: 192.168.188.129
    port: 6379
mybatis:
  mapper-locations: classpath:com/offcn/project/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    filter-only-up-instances: true
logging:
  level:
    com:
      offcn: debug #debug-->info-->warn-->error
  file:
    path: D:\log\scw-project
oss:
  endpoint: http://oss-cn-chengdu.aliyuncs.com
  bucketDomain: rui2021.oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI4G436PysT4HMkWUNhGJF
  accessKeySecret: 4CqKEfBN1JmJFbGuUCzA7wCK04JeHq
  bucketName: rui2021
